### ISSUE TITLE
Unable to get BeagleTerm to work with PL2303

### ISSUE THREAD

**Issue by jsquyres** [beagleterm/beagle-term#34]
I have a PL2303 USB-to-serial dongle that works fine with my MacBook pro (i.e., I can "screen /dev/tty.PL2303-*" in OS X and connect to whatever the USB-to-serial dongle is connected to).

However, when I plug the USB into my Chromebook and fire up BeagleTerm, BT identifies /dev/ttyUSB0 as a valid device, asks for the baud rate (I choose the highest -- 115200, although I've tried all the baud speeds, too), and lets me click on "CONNECT".

I see:

```
Welcome to Beagle Term version BETA.
Device found /dev/ttyUSB0 connection Id 1.
```

But then it is unresponsive.  Hitting enter to get a login prompt from the network switch I'm plugged in to, for example, yields nothing.

Is there something I need to do in ChromeOS to enable the use of BT with my USB-to-serial dongle properly?

Thank you!

**Comment by sunglim** [comment]
let me know if you still meet this issue
