### ISSUE TITLE
doesn't re-connected after the device reboot.

### ISSUE THREAD

**Issue by sunglim** [beagleterm/beagle-term#36]
device turn on -> beagle term connect -> device turn off -> device turn on.

doesn't re-connected after the device reboot.
chromium issue though.

**Comment by sunglim** [comment]
probably fixed from chromium side after implementing Mojo interface.

**Comment by RandomlyKnighted** [comment]
I'll test it out and verify just to be sure.

**Comment by sunglim** [comment]
Thanks @RandomlyKnighted !

**Comment by RandomlyKnighted** [comment]
@sunglim I just confirmed that this is in fact fixed. I connected to my Cisco 1811 router, turned off the router, then turned it back on all while leaving the BeagleTerm window open and it immediately showed output on the screen.

**Comment by sunglim** [comment]
@RandomlyKnighted  thank you for the confirm.
It sounds interesting that BeagleTerm is used with router. I heard many time about it.

**Comment by RandomlyKnighted** [comment]
Yeah so I don't know how it's done there but around here connections to enterprise grade equipment like Cisco switches and Cisco routes are generally done either via telnet or via a serial port connection. I managed to get a hold of a Cisco 1811 router to test with so I just hooked it up via serial port connection.
