### ISSUE TITLE
Display Issues

### ISSUE THREAD

**Issue by JordanKH** [beagleterm/beagle-term#4]
Hi there,
I am using Beagle Term on a Chromebook with a USB-2-Serial adapter. Beagle Term sees the adapter and is able to connect to my serial devices but I receive poor output on my display. There is an extra space and indentation to where the previous line finished which makes text hard to read. It's like there are too many line feed's and no carriage return. I have tried a Cisco router and a Dell switch with the same results. Is there anything we
can do to fix this. Thanks for the help!
Jordan

![Screenshot 2013-02-12 at 10 21 51 AM](https://f.cloud.github.com/assets/3577208/150011/9837fa90-7541-11e2-9cf1-86375844f6df.png)

**Comment by bzboi** [comment]
Hi, how do I configure Beagle Term for LF instead of CR+LF? I'm still seeing this issue with 1.8.2. Is this related to issue #19 ? Thanks.
