### ISSUE TITLE
Paste into beagle-term?

### ISSUE THREAD

**Issue by richardhkirkando** [beagleterm/beagle-term#40]
Is it possible to paste into beagle-term?  If so, how?  Ctrl+v, middle click, right click, etc do not work for me.

If not, consider this a feature request :)

**Comment by pr1ntf** [comment]
It looks like standard crosh rules apply. Use Ctrl+Shift+V to paste, Ctrl+Shift+C to copy.

**Comment by sunglim** [comment]
Im not sure standard crosh rules are working

Because Beagle term uses fairly old Hterm version

If its not working please let me know

2015년 5월 19일 화요일, pr1ntf<notifications@github.com>님이 작성한 메시지:

**Comment by richardhkirkando** [comment]
yes, ctrl-shift-c/v work.
