### ISSUE TITLE
Can not send commands

### ISSUE THREAD

**Issue by chisam14** [beagleterm/beagle-term#41]
I am using an HP Chromebook with a Belkin usb-serial adapter. Problem is that I can't get any kind of screen output from my equipment. Beagle term sees the usb port and I select the proper rate, it connects but will not take any keys. I can reboot the equipment and I start getting text across the screen then when the equip is fully up I can then issue commands. I do not want to have to reboot equipment every time I need to console in. Is there a fix for this?

**Comment by sunglim** [comment]
it is chromium serial api bug . afaik.

**Comment by chisam14** [comment]
Are you aware of a workaround or a fix in the near future? I bought the chromebook for work use but it is useless without a reliable serial terminal. Thanks

**Comment by sunglim** [comment]
It looks like chromeos driver issue.
you can file an issue on crbug.com/new
