### ISSUE TITLE
Tab key no longer working

### ISSUE THREAD

**Issue by richardhkirkando** [beagleterm/beagle-term#42]
Just noticed that tab auto completion when consoled into various network gear seems to have stopped working on my chromebook.  I remember there being a recent Chrome OS update - I can't be certain that this stopped working at the same time, but it seems likely-ish.  Let me know if there are any specific details I can provide.

**Comment by sunglim** [comment]
Thank you for reporting this. it seems like it's time to update hterm.
I'll add this to my todo list.

**Comment by sunglim** [comment]
Thanks to @korylprince , hterm is updated. I'll release new version on this weekend.

**Comment by sunglim** [comment]
Fixed in version 1.6
