### ISSUE TITLE
Question: What is the Connection ID used for?

### ISSUE THREAD

**Issue by RandomlyKnighted** [beagleterm/beagle-term#48]
I've noticed that each time a new connection is made the connection Id is incremented by one. What's the purpose of keeping up with this?

**Comment by sunglim** [comment]
Hi again,

BeagleTerm uses Connection ID when calling [chrome.serial.disconnect](https://developer.chrome.com/apps/serial#method-disconnect).

As you might know know, BeagleTerm doesn't generate Connection ID. When BeagleTerm calls chrome.serial api from [code](https://github.com/beagleterm/beagle-term/blob/e0638b66ec52b1128a9f60a7784e86b6e0f232d1/app/main.js#L96), chrome serial connect api returns connection id. and this ID is necessary to manipulate connection.

Feel free to ask any question!
