### ISSUE TITLE
Question: Why Polymer?

### ISSUE THREAD

**Issue by RandomlyKnighted** [beagleterm/beagle-term#49]
I created my own terminal app and have been able to [replicate the Beagle Term design](https://github.com/RandomlyKnighted/OpenTerm) using nothing more than Bootstrap and jQuery.  This project was nothing more than a test to see if the design could be replicated without Polymer. I've never used Polymer before so I've been reading up on it and I'm not sure I understand why it was chosen. Could you explain what made you decide to use it in this project?

**Comment by sunglim** [comment]
Hi @RandomlyKnighted ,

[Your project](https://github.com/RandomlyKnighted/OpenTerm) is awesome!

When I filed the issue(https://github.com/beagleterm/beagle-term/issues/21), I was thinking Polymer is good a method to implement Huge UI application and maintain easily.

But now I'm thinking BeagleTerm doesn't need heavy UI framework. Your design is pretty awesome.
PR is always welcome. 

Thank you for your ongoing interest!
