### ISSUE TITLE
Question: What is the project license?

### ISSUE THREAD

**Issue by RandomlyKnighted** [beagleterm/beagle-term#50]
In the package.json you have project's license listed as BSD and then in the bower.json file you have the project's license listed as MIT. Which one is the correct license?

**Note:** If the correct license is BSD then can you be more specific as to which BSD license it is? I've included below the list of approved BSD licenses that are accepted by both NPM and Bower:

| Full Name of License | License Identifer |
| ------------- | ------------- |
| BSD 2-clause "Simplified" License | BSD-2-Clause |
| BSD 2-clause FreeBSD License | BSD-2-Clause-FreeBSD |
| BSD 2-clause NetBSD License	| BSD-2-Clause-NetBSD |
| BSD 3-clause "New" or "Revised" License | BSD-3-Clause |
| BSD 3-clause Clear License | BSD-3-Clause-Clear | 
| BSD 3-Clause No Nuclear License | BSD-3-Clause-No-Nuclear-License	 |
| BSD 3-Clause No Nuclear License 2014 | BSD-3-Clause-No-Nuclear-License-2014 |
| BSD 3-Clause No Nuclear Warranty | BSD-3-Clause-No-Nuclear-Warranty |
| BSD 4-clause "Original" or "Old" License | BSD-4-Clause |
| BSD Protection License | BSD-Protection |
| BSD Source Code Attribution | BSD-Source-Code |
| BSD with attribution | BSD-3-Clause-Attribution |
| BSD Zero Clause License | 0BSD |
| BSD-4-Clause (University of California-Specific) | BSD-4-Clause-UC |

**Comment by sunglim** [comment]
I'll check. Thank you for asking !

**Comment by sunglim** [comment]
Added file https://github.com/beagleterm/beagle-term/blob/master/LICENSE that say `BSD-3-Clause`

**Comment by sunglim** [comment]
I mentioned my name on the top of https://github.com/beagleterm/beagle-term/blob/master/LICENSE.
But everyone who contributed this project has same authority as described.
