### ISSUE TITLE
Switch from Polymer to Bootstrap

### ISSUE THREAD

**Issue by RandomlyKnighted** [beagleterm/beagle-term#51]
As discussed in #49, it was agreed that Polymer is a bit too large of a framework to use with BeagleTerm. With that in mind it would be good to replace Polymer with something simpler like Bootstrap.

I have already begun work on this and hope to have a PR this weekend. I've already started working on this but still need to test what I've done so far. What has to be done in order to to publish a new version of the project? Is there anything I need to do to the project before I submit my PR?

**Comment by sunglim** [comment]
You should list you name on the <project repo>/AUTHOR  file.
And PR is enough,  if theres more things then we can discuss while code
review

2016. 9. 5. 오전 8:29에 "Tyler Hughes" <notifications@github.com>님이 작성:

**Comment by RandomlyKnighted** [comment]
Odd merging my PR should have closed this issue.
