### ISSUE TITLE
Misspelled serial in project description

### ISSUE THREAD

**Issue by RandomlyKnighted** [beagleterm/beagle-term#52]
As shown in the image below the word "serial" is incorrectly spelled as "seiral".

![beagle_term_spelling](https://cloud.githubusercontent.com/assets/2483249/18292687/2208834c-7454-11e6-8225-66ec09f34721.PNG)

**Comment by RandomlyKnighted** [comment]
This isn't a big issue at all it's just something I noticed earlier.

**Comment by sunglim** [comment]
Thanks :) fixed.
