### ISSUE TITLE
Release new version to chrome app store

### ISSUE THREAD

**Issue by sunglim** [beagleterm/beagle-term#54]
We should release next version. 1.7 on 15 September.

- [x] Remove polymer - @RandomlyKnighted

- [x] Remove 'Beta' from version.

- [x] Repacking and test - @sunglim

- [x] Update project description on CWS - @sunglim

- [x] Add options for data bit, parity, stop bit, and flow control - @RandomlyKnighted 

      we should show thanks list (+RandomlyKnighted)

**Comment by sunglim** [comment]
@RandomlyKnighted, FYI.

**Comment by RandomlyKnighted** [comment]
@sunglim One thing I just noticed is that you said the next version is 1.8. The current version is actually 1.6. I just went ahead in my PR and updated the numbers to 1.7 so save us a step later on.

**Comment by RandomlyKnighted** [comment]
@sunglim so are we just going to release with an updated UI or do we want to try and get a new feature in before the release?

**Comment by sunglim** [comment]
@RandomlyKnighted  
No more new feature. I just have a thought to write script to pack easily on /tools/packing.py.

But feel free to send a PR! for example, setting parity bit. it is always welcome.

**Comment by RandomlyKnighted** [comment]
That's what I meant. I didn't know if you wanted to try and get the parity issue stuff added before we release.

**Comment by sunglim** [comment]
@RandomlyKnighted  feel free :)

**Comment by RandomlyKnighted** [comment]
Are we still planning to release today?

**Comment by sunglim** [comment]
> Are we still planning to release today?
Yes, I'm packing now

**Comment by sunglim** [comment]
by the way, from next version, we might need to release 'unstable' version first. I'm a little not sure if everything is fine or not.

**Comment by RandomlyKnighted** [comment]
That's fine. Do we want to define how long a release will be deemed unstable before switching it to stable?
