### ISSUE TITLE
What functionality are we getting from hterm?

### ISSUE THREAD

**Issue by RandomlyKnighted** [beagleterm/beagle-term#55]
I see that we're using `hterm_all.js`; however, the only time we're referencing it is when we're [loading the window](https://github.com/beagleterm/beagle-term/blob/master/app/js/index.js#L75-L84). What functionality is this library giving us?

**Comment by sunglim** [comment]
Hi again

Thanks to @rginda, [hterm ](https://chromium.googlesource.com/apps/libapps/+/master/hterm) provides a terminal emulator.  it draws entire things except frame window.

Beagleterm is connected to hterm when loading the window(Your can see `Crosh` object is passed). After that, when we receive strings from chrome.serial API, Beagleterm just forward received string from chrome.serial api to hterm.  See https://github.com/beagleterm/beagle-term/blob/3ab6b4d4ba9f22135944a6d6b4c040b2aa5774b8/app/js/index.js#L30
