### ISSUE TITLE
Make JSHint  automatically via CI

### ISSUE THREAD

**Issue by sunglim** [beagleterm/beagle-term#59]
Since `Gruntfile.js` already checks `JSHint`. So runing grunt task via CI is enough.

**Comment by RandomlyKnighted** [comment]
There's already a JSHint ready to use in the `Gruntfile.js`. Are you wanting it to run automatically via CI or do you mean something else with this issue?

**Comment by sunglim** [comment]
> Are you wanting it to run automatically via CI or do you mean something else with this issue?
via CI.

I'm going to create something like /tools/run-all-js-test.py  that runs jshint for all directories. and run it via CI.
Thank you for your comment. Feel free to share any idea.

**Comment by RandomlyKnighted** [comment]
In some of the open source project's I've worked on in the past we've just made the CI run the grunt task. By doing it that way any jshint errors will show up as a failed check on the PR. The PR can't be merged until it passes the check. It's pretty much the same concept as your CLA bot. 

You can also integrate jscsrc with jshint to enforce the Google Style Guide.

**Comment by sunglim** [comment]
Thank for the info, It sounds like we can run grunt task on CI. I updated issue description.
