### ISSUE TITLE
extension validation fail when loading

### ISSUE THREAD

**Issue by sunglim** [beagleterm/beagle-term#66]
![image](https://cloud.githubusercontent.com/assets/756988/18500447/6fab9722-7a82-11e6-86a5-55210b08f806.png)

I don't understand why I didn't meet this until now.

TEST steps:
 1. git clone
 2. npm install
 3. load extension from chrome

**Comment by RandomlyKnighted** [comment]
It didn't do that for me until I deleted my project directory and re-cloned the project. I cloned both your repo and my fork and it happens on both. This is weird, because I cloned my fork yesterday on another computer and I didn't run into this issue at all.
