### ISSUE TITLE
BeagleTerm 1.7 is released!

### ISSUE THREAD

**Issue by sunglim** [beagleterm/beagle-term#68]
Hi all,

I have released version 1.7.

You can download from below URL.
Please please let me know when you meet any issues.

https://chrome.google.com/webstore/detail/beagle-term/gkdofhllgfohlddimiiildbgoggdpoea?utm_source=chrome-ntp-icon

@jumanjiman, @RandomlyKnighted

**Comment by RandomlyKnighted** [comment]
I get an error 404 when I visit that link.

**Comment by sunglim** [comment]
| I get an error 404 when I visit that link.

I believe it soon will be available in < 30min

**Comment by RandomlyKnighted** [comment]
Ok, the Chrome store now says version 1.7.0. I'm just waiting for the app to update on my computer.

**Comment by sunglim** [comment]
@RandomlyKnighted , I really appreciate your effort!! You made BeagleTerm breathes again.

**Comment by RandomlyKnighted** [comment]
Got the update, looks good!

No problem, happy to help.
