### ISSUE TITLE
Unable to talk to a device on Chrome OS

### ISSUE THREAD

**Issue by RandomlyKnighted** [beagleterm/beagle-term#71]
At my work, we're currently demoing am Asus C100P Chromebook. I tried connecting to 2 different switches, first a Brocade 6450 24-port switch and second an Enterasys C5 48-port switch. During boot up of the switches, I kept getting a bunch of question marks on the screen in random places. When each device finished booted I tried hitting the enter key so it would take me to the login prompt, however, nothing would happen. It's as if Beagle Term is unable to communicate with these devices when on a Chrome OS device.

I then tried hooking the same USB to serial adapter into my desktop and tried connecting to the switches. They worked without a problem. So it definitely seems like an issue with Chrome OS.

**Comment by sunglim** [comment]
Well. It seems like the driver is not supported in Chrome side. 

Simillar issue https://bugs.chromium.org/p/chromium/issues/detail?id=446902&q=chrome.serial&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Component%20Status%20Owner%20Summary%20OS%20Modified

**Comment by RandomlyKnighted** [comment]
I commented on the issue and included the model of my Chromebook. 

I did notice that the port dropdown lists my adapter as USB0. Because it recognizes it that way wouldn't it mean that the driver is there?

**Comment by sunglim** [comment]
> I did notice that the port dropdown lists my adapter as USB0. Because it recognizes it that way wouldn't it mean that the driver is there?

Well. AFAIK, normally in windows,  Without installing proper driver, we can see the port.  I'm not sure though.

**Comment by RandomlyKnighted** [comment]
You can see Port 1, because that's the Communication Port it's built into Windows itself. When I plug in my adapter, it sees a new port (i.e. PORT4). Though I'm not sure if Chrome OS works the same way or not.

**Comment by RandomlyKnighted** [comment]
@sunglim Is there any way we can get your contact on the Chromium team to look into the issue you linked to above? I'd love to be able to test this release on a Chromebook.

**Comment by sunglim** [comment]
Sorry for being late.

@RandomlyKnighted Sadly I can't. Since their priority is depends on Google's policy.
I think the best way is that to implement by ourselves.

**Comment by RandomlyKnighted** [comment]
I'm not sure I follow. You want to create your own driver for Chromebooks or just install it yourself like you would on a Windows PC?

**Comment by RandomlyKnighted** [comment]
@sunglim I noticed this afternoon that the Chromebook I've been demoing had a couple of Chrome OS updates. I've went ahead and installed the updates but I didn't think to bring my adapter with me to work today. Is there a way to check if the driver has been installed? For example on Windows, drivers are stored in `C:\Windows\system32`

**Comment by RandomlyKnighted** [comment]
So maybe I'm missing something but here's what I see when I use the Asus C100P Chromebook.  As you can see in the image below when I open Beagle Term (**without** my adapter connected) I don't get anything listed in the port dropdown.

![beagle-term_no_device](https://cloud.githubusercontent.com/assets/2483249/19126186/90540a94-8aff-11e6-83a0-71a31aef51f3.png)

When I close BeagleTerm and reopen it with the adapter connected it shows my adapter listed. You can see this in the screenshot below.

![beagle-term_with_device](https://cloud.githubusercontent.com/assets/2483249/19126203/97fd73b6-8aff-11e6-8a97-4589da3ef487.png)


Once I create my connection it shows that it connected via that port on connection ID 2. I then boot up the device and all my output looks like the image below:

![beagle-term_weird_output](https://cloud.githubusercontent.com/assets/2483249/19126210/9a9af04e-8aff-11e6-9d87-34745ac88f1f.png)

@sunglim do you still think the driver's missing even though it shows the adapter in the list? I know in Windows if the driver is missing then it doesn't show it in the dropdown. To me it seems like this may actually be some other issue.

**Comment by sunglim** [comment]
>  I know in Windows if the driver is missing then it doesn't show it in the dropdown.

Are you sure about this? I'm not sure as well. But as I experienced with graphic card on PC, if the driver is outdated, we can stil see the screen but it is broken,

and. Could you please share a debugging information?
From https://github.com/beagleterm/beagle-term/blob/3af95870b76f3447c7489b3de3d9f59d31a99032/app/js/index.js#L218
You can just add `console.log(info.data)`.  let's see it.

@reillyeon Could you please share your wisdom? It seems like `[chrome.serial.onReceive](https://developer.chrome.com/apps/serial#event-onReceive)` give us wrong data. I believe this is driver problem in ChromeOS.

**Comment by RandomlyKnighted** [comment]
> Are you sure about this? I'm not sure. But as I experienced with graphic card on PC, if the driver is outdated, we can still see the screen but it is broken,

Well the day I got my adapter, before I ever plugged it into my PC I open BeagleTerm and the only adapter that showed up was the default COM1 Communications port. So I closed BeagleTerm, plugged in my adapter, and reopened BeagleTerm. At that point I now had COM1 and COM3. I did some testing and found out that COM3 was the adapter. I've also seen this happen when programming via serial port in C#.

> and could you please share a debugging information? From https://github.com/beagleterm/beagle-term/blob/3af95870b76f3447c7489b3de3d9f59d31a99032/app/js/index.js#L218 You can just add console.log(info.data). let's see it.

How would I go about updating this and installing it on the Chromebook? All my development is done on PC.

**Comment by sunglim** [comment]
> How would I go about updating this and installing it on the Chromebook? All my development is done on PC.

You can build your own package. and load it from `chrome://extensions`.

> I'd also like to add that I also tested BeagleTerm on a Dell P22T Chromebook (11 inch) and had the same results you see above.

Chromebook and linux share same driver. If you can use Windows laptop or Macbook. we can make sure the problem exist in Linux(including ChromeOS).

**Comment by sunglim** [comment]
> Is there a way to check if the driver has been installed?

Hm.. I don't know now. but I'll take a look

**Comment by RandomlyKnighted** [comment]
> Chromebook and linux share same driver. If you can use Windows laptop or Macbook. we can make sure the problem exist in Linux(including ChromeOS).

I know it works on a Windows 10 desktop. I tested it on two of them before we released the update. I haven't tested on a MacBook though.

> You can build your own package. and load it from chrome://extensions.

You have to zip the files up and load that, correct?

**Comment by sunglim** [comment]
@RandomlyKnighted 
Which `USB to serial adapter` do you use?  We might need to find out the chip name on your `usb to serial adaptor`  If your `USB to serial adapter` uses `cp210x` chip. then it must be driver issue.

> I know it works on a Windows 10 desktop. I tested it on two of them before we released the update. I haven't tested on a MacBook though.

I think this also means the culprit is driver.

**Comment by sunglim** [comment]
>>  Is there a way to check if the driver has been installed?

> Hm.. I don't know now. but I'll take a look

Here's a code[1] for chromeos 4.4.  As you can see a lot of driver is `not set`. Let's find out which chip your `USB to serial adapter` use. and let's modify the chromeos kernel code by ourselves.

[1] enabled driver list for chrome os 4.4. https://chromium.googlesource.com/chromiumos/third_party/kernel/+/release-R54-8743.B-chromeos-4.4/chromeos/config/base.config#2451

**Comment by sunglim** [comment]
Adding `Blocked` label since this issue should be fixed in Chromium side.
But we still try to fix chrome code by ourselves.

**Comment by RandomlyKnighted** [comment]
> Which USB to serial adapter do you use? We might need to find out the chip name on your usb to serial adaptor If your USB to serial adapter uses cp210x chip. then it must be driver issue.

@sunglim This is the [adapter I've been using](https://www.amazon.com/gp/product/B001J226JQ/ref=oh_aui_detailpage_o03_s00?ie=UTF8&psc=1).

**Comment by sunglim** [comment]
@RandomlyKnighted thanks. hm but it's not easy to find the chip name. I'll try to find the chip name again.

**Comment by sunglim** [comment]
Your adapter's chip name is CP341 and it is enabled on ChromeOS 4.4. 
Which version is your chromeos?

>>You can build your own package. and load it from chrome://extensions.

> You have to zip the files up and load that, correct?

You can build your own package on your PC and send it to email. download it from your chrome book. unzip and open in chrome://extensions.

**Comment by RandomlyKnighted** [comment]
I don't know the version. I work in a school system and we're out on Fall break until Wed. I'll check it out then. 

By the way, how did you find the adapter''s chip name?

**Comment by sunglim** [comment]
> By the way, how did you find the adapter''s chip name?

I can catch that the driver is either CH340 or CH341 by the review of Amazon.
and I can realize that CH341 has a power to run both CH341 and CH340 by http://forum.odroid.com/viewtopic.php?f=111&t=9972

**Comment by RandomlyKnighted** [comment]
I'm about to make the logging change and test that out. 

I wanted to mention that I also have [this adapter](https://www.amazon.com/gp/product/B01B4ZSMQI/ref=oh_aui_detailpage_o00_s00?ie=UTF8&psc=1) on hand. When I plug it in and open BeagleTerm it doesn't show the adapter listed at all. It looks like either the driver either isn't install it or it's not enabled by default. 

I'll comment back here when I have the output of the log.

**Comment by RandomlyKnighted** [comment]
Alright I was able to install it by making the change, zipping the file, sent it to myself, unzipped it and loaded it via Developer Mode. I opened BeagleTerm and saw the normal connection created message so I tried to open the developer console to see the info. Unfortunately, I wasn't able to get it to open. When I try and right click in the window, nothing happens. Is hterm doing something to prevent me from right clicking in the black terminal area?

**Comment by sunglim** [comment]
@RandomlyKnighted  Thanks for your effort. 

To see the developer console for chrome app, you can open it from `chrome://extension` menu.

i.e.
1. Run BeagleTerm
2. Open `chrome://extension` on your chrome
3. Click `index.html`.  it will open developer console.

![image](https://cloud.githubusercontent.com/assets/756988/19348786/940b25f0-918a-11e6-9559-b56136d1c127.png)

Hope it works.


PS. could your share your ChromeOS version?

**Comment by RandomlyKnighted** [comment]
On the Asus C100P Chromebook here's my version number:

```
Version 53.0.2785.144
Platform 8530.93.0 (Official Build) stable-channel veyron_minnie
ARC Version 3301557
Firmware Google_Veyron_Minnie.6588.197.0
```

**Comment by RandomlyKnighted** [comment]
I opened the Dev Console before attempting to connect to the device. When I hit connect no messages show up in the console. So what I did next was I rebooted the device and as soon as I did it started logging a whole bunch of stuff. Looking the logs over it looks like hterm is giving the same 3 warnings over and over again: 
```
Ignored CC1 code: \u0011
Ignored CC1 code: \u0005
Ignored CC1 code: \u0013
```

The console.log line I added also popped up a bunch of times. They all look like this:

```
ArrayBuffer {}
```

When I dig deeper into it I see that the byteLength varies each time it's being logged.

**Comment by RandomlyKnighted** [comment]
@sunglim do you have any advice based on the output I posted above?

**Comment by sunglim** [comment]
It seems that chromos on your chromebook already includes correct driver(CH341).
https://chromium.googlesource.com/chromiumos/third_party/kernel/+/stabilize-8530.93.B-chromeos-4.4/chromeos/config/base.config#2444

About `ArrayBuffer {}`.
As you might know Chrome sends byte data as `ArrayBuffer`. But it is empty.

Weird.  If you use another USB to serial adapter(which doesn't use CH341) ,  you might be able to circumvent this issue.

**Comment by RandomlyKnighted** [comment]
Do you know of another adapter that I can buy that should work? I'm happy to give it a try.

**Comment by sunglim** [comment]
@jumanjiman, @ShannonVanWagner, @mdv55
Hey folks, could you kindly share which USB to serial adapter you're using?

**Comment by jumanjiman** [comment]
sorry, i've moved to a different place and don't have an adapter at the moment.

**Comment by ShannonVanWagner** [comment]
Keyspan usa-19hs by tripp lite is the one I've tested.

**Comment by RandomlyKnighted** [comment]
Thanks @ShannonVanWagner. I just ordered it on Amazon. Have you tested with that adapter on Chrome OS since our last release?

**Comment by RandomlyKnighted** [comment]
I'm going to try and get myself a Chromebook during the holiday sales. Once I get one I'll test this out and will report back. In the mean time I'll go ahead and close this issue. If I find that it doesn't work I'll reopen it.

**Comment by sunglim** [comment]
👍
