### ISSUE TITLE
New version (maybe) hangs on connect

### ISSUE THREAD

**Issue by theotang** [beagleterm/beagle-term#72]
I am not sure if it is because of the new version of Beagle Term or if it is because of ChromeOS updates, but now when I press connect, my Chromebook hangs.  The only way to free it, is to unplug the USB-serial adapter.

How do I troubleshoot what is wrong here?  This used to work in the previous version.

I've tried 3 different USB-serial adapters that had previously worked, same results.  I've tried both USB ports on my Chromebook.

I also removed Beagle Term and re-installed it.  Also rebooted my Chromebook.

Is there a way to try the old version somewhere?

I really liked being able to serial console into switches and routers.

**Comment by RandomlyKnighted** [comment]
Have you verified that the settings you used for data bit, flow control, and stop bit match your switches recommended settings? For most routers the data bit is set to 8 bit, flow control is none, and stop bit is set to 1 bit.

**Comment by theotang** [comment]
I tested again with my CR-48 and it worked.  Guess I might have to power wash my Acer.

**Comment by sunglim** [comment]
closing by above comment.

**Comment by sunglim** [comment]
The only change from old version is UI.
(We all knows that re-connection USB-serial adapter will make it work.)

**Comment by theotang** [comment]
FYI, I was in developer mode on my Acer experiencing the hang problem.  I exited developer mode and it still had the same problem.  I finally did a power wash and it now works.  Must have been a messed up driver in the OS for my USB-serial adapter.
