### ISSUE TITLE
Higher baudrate support

### ISSUE THREAD

**Issue by eeyrw** [beagleterm/beagle-term#74]
Recent usb-ttl dongle and embedded device can support baudrate up to 460800. It could be useful if support extend baudrate option in app:

> 128000
> 153600  
> 230400
> 256000
> 460800
> 921600

Thanks.

**Comment by sunglim** [comment]
Thank you for the reporting.

We can implement it by adding more options at below
https://github.com/beagleterm/beagle-term/blob/master/app/index.html#L44

PR is always welcome.
