### ISSUE TITLE
v1.8.0 beta release

### ISSUE THREAD

**Issue by sunglim** [beagleterm/beagle-term#76]
You can get v1.8.0 beta from https://chrome.google.com/webstore/detail/beagle-term-beta/bgoacdphmdhhogadlgbhkpopljionhie?utm_source=chrome-ntp-icon

Feature added.
- https://github.com/beagleterm/beagle-term/issues/74: Higher baudrate support

@eeyrw If you can find time, feel free to run it and let us know if there's any issue. Thank you for your contribution again!

**Comment by eeyrw** [comment]
![image](https://cloud.githubusercontent.com/assets/2088817/19879616/853e106a-a02f-11e6-9403-05b0f0593d52.png)
It works under baud rate of 460800. Other baud rates are not tested, but it should be fine.

**Comment by sunglim** [comment]
@eeyrw Thank you! I'll release official version then.
