### ISSUE TITLE
locks up when attempting to connect 9600 

### ISSUE THREAD

**Issue by baileyds** [beagleterm/beagle-term#77]
Beagleterm locks up Chromebook when attempting to connect via usb adapter, 9600 bitrate.

Pulling the USB to serial adapter restores the Chromebook back to functionality, but Beagleterm (of course) does not connect.

Further info:
Dell Chromebook 13 model 7310
USB to serial adapter - sadly unsure of model. Silver cable, used 2, also same ones I had used before the recent Beagleterm update.
Switch in question: Extreme x440-48t

Serial connection info: http://oi63.tinypic.com/2wn8hzc.jpg

ChromeOS
Google Chrome	54.0.2840.51 (Official Build) beta (64-bit)
Revision	0
Platform	8743.57.0 (Official Build) beta-channel lulu
JavaScript	V8 5.4.500.31
Flash	23.0.0.185-r1

Un/reinstalling Beagleterm does not change the symptoms. 

Thanks for any advice.

**Comment by sunglim** [comment]
ChromeOS Beta channel is very unstable. I recommend to use ChromeOS stable channel.

**Comment by baileyds** [comment]
Thanks sir - I was noticing that as I submitted the bug report.  Will do and will report back.

**Comment by baileyds** [comment]
That appeared to be the issue - used a c720 on stable OS channel, works great.  Thanks.
