### ISSUE TITLE
Locks up when opening a connection

### ISSUE THREAD

**Issue by RandomlyKnighted** [beagleterm/beagle-term#78]
I'm experiencing the same issue mentioned in #77; however, the Chromebook I'm using is already on the stable channel. Here's the info on the Chromebook:

```
Google Chrome OS
Version 54.0.2840.79
Platform 8743.76.0 (Official Build) stable-channel veryron_minnie
ARC Version 3388537
Firmware Google_Veyron_Minnie.6588.197.0
```

Any suggestions on what I should do?

**Note:** I am using the latest version of Beagle Term.

**Comment by sunglim** [comment]
ChromeOS is locked up? or only BeagleTerm is locked up?

**Comment by RandomlyKnighted** [comment]
ChromeOS locks up when I hit the Connect button.

**Comment by sunglim** [comment]
interesting. i'll take a look if there's any change on chrome side.

**Comment by baileyds** [comment]
I'd like to chime back in on this - same issue here now back on a CB on stable channel.  

Dell Chromebook 13 model 7310; note this does not seem to happen using an Acer C720, same usb to serial converter cable, also via BeagleTerm.

Version 54.0.2840.79 (64-bit)
Platform 8743.76.0 (Official Build) stable-channel lulu
Firmware Google_Lulu.6301.136.57

Let me know if I can help / get more info.  I can mitigate the lockup by pulling out the usb to serial converter - beagleterm window stays open but not connected to anything (obviously)

**Comment by RandomlyKnighted** [comment]
I tested earlier to see if it only affects the 9600 bitrate and it does not. I had the same results no matter what bitrate I chose.

**Comment by gyldenro** [comment]
I can confirm having same issue on Toshiba CB30 (first generation)

Version 54.0.2840.79 (64-bit)
Platform 8743.76.0 (Official Build) stable-channel leon
Firmware Google_Leon.4389.61.46

**Comment by RandomlyKnighted** [comment]
@sunglim any news? I'm starting a new job on Monday and won't have access to a Chromebook after Thursday.

**Comment by ram1977** [comment]
Same problem on a Acer CB3-531

Versie 54.0.2840.79 (64-bit)
Platform 8743.76.0 (Official Build) stable-channel banjo
Firmware Google_Banjo.5216.334.4

Also on the Beta channel it wont work.
I think it's Chrome related because al extentions that make a serial connection are freezing.

**Comment by sunglim** [comment]
sorry for being late. I asked to some googlers and waiting for response.

**Comment by baileyds** [comment]
No problem, your responsiveness is fantastic.

If I can help please let me know.

Damian Bailey, MCP
Coordinator of Technology Services
LCPS Technology

Sent by MailWise<http://www.mail-wise.com/installation/2> – See your emails as clean, short chats.


-------- Original Message --------

**Comment by omegaseiko** [comment]
I am having the same issue.  Clicking on connect freezes Chromebook - Dell Chromebook 11 on stable, developer mode.  Chromebook recovers as soon as I pull out Keyspan.

**Comment by sunglim** [comment]
there're 4 patches between previous version and current version on chromium side.
I'm bisecting now..
But sadly if I found the culprits and submit a patch. it takes more than 1month to next ChromeOS release :(

**Comment by RandomlyKnighted** [comment]
Is the ["Estimated* Stable Dates"](https://www.chromium.org/developers/calendar) the same patches you were talking about or did you find this somewhere else?

**Comment by sunglim** [comment]
Who will win the president election? what do you say?

**Comment by RandomlyKnighted** [comment]
haha it's going to be close but I think it will be Trump

**Comment by sunglim** [comment]
> Is the "Estimated* Stable Dates" the same patches you were talking about or did you find this somewhere else?

Yes. serial code lives under [device/serial](https://cs.chromium.org/chromium/src/device/serial/). and found the diff between two git tags.

**Comment by sunglim** [comment]
I can reproduce this issue. Obviously my chromebook locked when `chrome.serial.connect` is called

**Comment by sunglim** [comment]
Fixed in chromium side.

**Comment by ram1977** [comment]
Thanks for the great support. How often they release a Chrome update?

**Comment by sunglim** [comment]
By https://www.chromium.org/developers/calendar , it term is approximately 6 weeks.
If you can't wait, You can switch to beta channel. chrome released daily on beta channel. for details see https://support.google.com/chromebook/answer/1086915?hl=en

**Comment by ram1977** [comment]
still no solution in Beta channel and development :(

**Comment by afra-git** [comment]
It worked a couple of weeks ago.  There must have been an update. Now it doesn't. My device may have been in developer's mode.

**Comment by sunglim** [comment]
No worries. This issue has fixed by one Googler. now the only thing we can
do is just waiting.
it soon will be working in either beta or canary channel.

**Comment by kristianpaul** [comment]
Same issue on Hisense :(

Version 54.0.2840.93
Platform 8743.83.0 (Official Build) stable-channel veyron_jerry
Firmware Google_Veyron_Jerry.6588.197.0

**Comment by sunglim** [comment]
@kristianpaul  Thank you for the reporting. as mentioned above, fix is sumitted but it be shipped to next update :(

**Comment by AADIP** [comment]
This is fixed for me on the R11 with an update from today.

Version 54.0.2840.101 (64-bit)
Platform 8743.85.0 (Official Build) stable-channel cyan
ARC Version 3487238
Firmware Google_Cyan.7287.57.82

**Comment by sunglim** [comment]
@AADIP  thank you for sharing updated info! closing then.
