### ISSUE TITLE
Support for copy and paste?

### ISSUE THREAD

**Issue by holelattanuttin** [beagleterm/beagle-term#88]
The one thing that is keeping me from using my Chromebook for everything is the lack of copy and paste to and from the session.  This app is versatile, flexible and eliminates the need to install buggy drivers, so it is awesome.  It also gets up and running very, very quickly.  The lack of copy and paste makes me carry a separate laptop (Windows, eek).

Thank you.

**Comment by Habbie** [comment]
ctrl-shift-c and ctrl-shift-v work fine on my Chromebook, did you try those combinations?

**Comment by holelattanuttin** [comment]
Thank you!  Why was I only trying cntrl-c and ctrl-v????

**Comment by codewithtyler** [comment]
Glad to hear this resolved your issue. I'm going to go ahead and close this issue.
